# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

version = 1

[[annotations]]
path = [
     "excluded-repos.json",
     "LICENSE"
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2026 The Linux Foundation"
